name: Deployment
on: push
jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Packages
      run: npm install
    - name: Run ESLint
      run: eslint . --ext .js,.jsx,.ts,.tsx
    - name: Build page
      run: npm run build
    - name: Deploy to Heroku
      uses: akhileshns/heroku-deploy@v3.5.6 # This is the action
      with:
        heroku_api_key: ${{secrets.HEROKU_KEY}}
        heroku_app_name: ${{secrets.HEROKU_APP}}
        heroku_email: ${{secrets.HEROKU_EMAIL}}